# https://pytorch-lightning.readthedocs.io/en/latest/api/pytorch_lightning.callbacks.ModelCheckpoint.html

# Save the model periodically by monitoring a quantity.
# Look at the above link for more detailed information.
model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint
    dirpath: null
    filename: null
    monitor: val/loss
    verbose: True
    save_last: True
    save_top_k: 5
    mode: min
    auto_insert_metric_name: True
    save_weights_only: False
    every_n_train_steps: null
    train_time_interval: null
    every_n_epochs: null
    save_on_train_epoch_end: null